name: Lint commit messages
on:
  push:
    branches:
      - main
      - 'renovate/**'
      - 'github-renovate/**'
  pull_request:
jobs:
  commitlint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # renovate: tag=v2.3.4
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@25316bbc1f10ac9d8798711f44914b1cf3c4e954 # renovate: tag=v2.4.0
        with:
          node-version: 14
      - name: Install project
        run: npm ci --ignore-scripts
      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@59203cb6ee1ce85035e6fe7b3aa878cf80653739 # renovate: tag=v4.1.1
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
