name: Lint commit messages
on:
  push:
    branches:
      - master
      - 'renovate/**'
      - 'github-renovate/**'
  pull_request:
jobs:
  commitlint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14
      - name: Install project
        run: |
          npm ci --ignore-scripts
          echo "::set-env name=NODE_PATH::$GITHUB_WORKSPACE/node_modules"
      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v2.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
