name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    if: |
      github.event.commits[0].message == 'chore(release): trigger release process [ci release]' ||
      github.event.commits[0].message == 'chore(release): trigger release process [ci release][major]' ||
      github.event.commits[0].message == 'chore(release): trigger release process [ci release][minor]' ||
      github.event.commits[0].message == 'chore(release): trigger release process [ci release][patch]'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: git fetch --tags
      - name: Setup Git user
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install project
        run: npm ci
      - name: Release
        run: |
          readonly COMMIT_MESSAGE="${{ github.event.commits[0].message }}"
          if [[ "${COMMIT_MESSAGE: -11: -1}" == 'ci release' ]]; then
            echo "::set-env name=NEXT_VERSION::$(npm run release:version --silent)"
            npx --no-install standard-version
          else
            readonly RELEASE_TYPE="${COMMIT_MESSAGE: -6: -1}"
            echo "::set-env name=NEXT_VERSION::$(
                npm run release:version --silent -- --releaseAs "${RELEASE_TYPE}"
                )"
            npx --no-install standard-version --release-as "${RELEASE_TYPE}"
          fi
      - name: Publish release
        run: git push --follow-tags
      - name: Publish GitHub release
        uses: actions/create-release@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.NEXT_VERSION }}
          release_name: v${{ env.NEXT_VERSION }}
          body: |
            See the the [changelog](
              https://github.com/${{ github.repository }}/blob/master/CHANGELOG.md
            ) for the changes included in this release.
  prevent_failed_status:
    name: Prevent failed status when skipped
    runs-on: ubuntu-latest
    steps:
      - name: Prevent failed status when skipped
        run: |
          echo "Run this job to prevent the workflow status from showing as" \
               "failed when all other jobs are skipped."
